imx8m: soc.c: fixed duplicate definition of get_effective_memsize()
Moved phys_size_t get_effective_memsize(void) under
      #ifndef CONFIG_IMX8M_BOARD_INIT_DRAM
This fixes compilation error: multiply definition of get_effective_memsize

Signed-off-by: FrancescoFerraro <francesco.f@variscite.com>
(cherry picked from commit 41e931344d7c1b63c1eb49a545de28b325a7d2ba)