imx8mm/spl_board_init: Don't call sec_init if SPL_CRYPTO missing
When trying to enable `DM_RNG` without `SPL_CRYPTO` the build fails with

    aarch64-pyxis-linux-ld.bfd: board/variscite/imx8mm_var_dart/spl.o: in function `spl_board_init':
    imx8mm_var_dart_config/../board/variscite/imx8mm_var_dart/spl.c:242: undefined reference to `sec_init'

Therefore, do the call of `sec_init()` to only in case `SPL_CRYPTO` is
enabled.

Signed-off-by: Jörg Sommer <joerg.sommer@navimatix.de>