MLK-14945 HAB: Check if IVT valid before authenticating image
For proper authentication users must check the IVT before authenticating the
kernel image. If the IVT DCD pointer is not 0, display an error as shown below
and return a boot failure.

	Authenticate image from DDR location 0x12000000...
        Error: DCD pointer must be 0

        Authenticate zImage Fail, Please check

Backported to branch imx_v2015.04_4.1.15_1.0.0_ga.

Signed-off-by: Utkarsh Gupta <utkarsh.gupta@nxp.com>
Signed-off-by: Breno Lima <breno.lima@nxp.com>
Signed-off-by: Eran Matityahu <eran.m@variscite.com>

Conflicts:
    arch/arm/imx-common/hab.c