mach-imx: imx8m: soc: Fix duplicated definition of get_effective_memsize()
Moved phys_size_t get_effective_memsize() under
  #ifndef CONFIG_IMX8M_BOARD_INIT_DRAM

This fixes compilation error: multiply definition of
get_effective_memsize.

Signed-off-by: FrancescoFerraro <francesco.f@variscite.com>
(cherry picked from commit a45559f644edcb034cc359e9af503faea418761d)