common: splash_source: add undeclared variable
Due to a missing variable declaration, the build would fail with
the following error:

  CC      common/splash.o
  CC      common/splash_source.o
common/splash_source.c: In function ‘splash_source_load’:
common/splash_source.c:467:9: error: ‘devpart’ undeclared (first use in this function); did you mean ‘dev_t’?
  467 |         devpart = env_get("splashdevpart");
      |         ^~~~~~~
      |         dev_t
common/splash_source.c:467:9: note: each undeclared identifier is reported only once for each function it appears in
make[1]: *** [scripts/Makefile.build:257: common/splash_source.o] Error 1
make: *** [Makefile:1848: common] Error 2

Declare devpart variable before it is used.

Signed-off-by: Diego Dorta <diego.d@variscite.com>